# Generated by Django 4.0.4 on 2022-04-27 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_min', models.IntegerField(verbose_name='Минимум лет выплат')),
                ('term_max', models.IntegerField(verbose_name='Максимум лет выплат')),
                ('rate_min', models.FloatField(verbose_name='Минимальный процент выплат')),
                ('rate_max', models.FloatField(verbose_name='Максимальный процент выплат')),
                ('payment_min', models.PositiveBigIntegerField(verbose_name='Сумма от')),
                ('payment_max', models.PositiveBigIntegerField(verbose_name='Сумма до')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bank_Offer', to='selection.bank', verbose_name='Привязанный банк')),
            ],
            options={
                'verbose_name': 'Ипотека',
                'verbose_name_plural': 'Ипотеки',
            },
        ),
    ]
